# Habilita o suporte a GPIO (para os LEDs)
CONFIG_GPIO=y

# Habilita o console para vermos a saída do printf/printk
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Aumenta o tamanho da pilha da thread principal, uma boa prática
CONFIG_MAIN_STACK_SIZE=2048

# Habilita suporte a nomes de threads para depuração
CONFIG_THREAD_NAME=y